# Generated by Django 4.2.17 on 2025-01-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.CharField(max_length=25)),
                ('difficulty', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
